version: '3'
services:
        web:
                image: stocks_v1
                build: .
                ports:
                        - "8087:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/P3T3_stocks/volumes
