name: Deploy to Server
on: [push]
jobs:
  AWS-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo SSH_KEY | base64 -d > key.pem
      - run: chmod 400 key.pem
      - run: ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@nighthawkcodescrums.gq 'cd ~/P3T3_stocks; git pull; docker-compose down; docker-compose up -d --build'
